#ifndef PIECES_CPP_
#define PIECES_CPP_
/*
enum class Pieces {BLACK=-1, WHITE=1, NEUTRAL=0,
                    WHITEPAWN=2, WHITEROOK=3, WHITEKNIGHT=4, WHITEKINGBISHOP=5,
                    WHITEQUEENBISHOP=6, WHITEKING=7, WHITEQUEEN=8,
                    BLACKPAWN=-2, BLACKROOK=-3, BLACKKNIGHT=-4, BLACKKINGBISHOP=-5,
                    BLACKQUEENBISHOP=-6, BLACKKING=-7, BLACKQUEEN=-8};
*/
enum class Pieces {BLACK=-1, WHITE=1, NEUTRAL=0,
                    WHITEPAWN=2, WHITEROOK=3, WHITEKNIGHT=4, WHITEBISHOP=5,
                    WHITEKING=6, WHITEQUEEN=7,
                    BLACKPAWN=-2, BLACKROOK=-3, BLACKKNIGHT=-4, BLACKBISHOP=-5,
                    BLACKKING=-6, BLACKQUEEN=-7};
                    
#endif //!PIECES_CPP_